#! /bin/sh
bspc rule -r *
killall "sxhkd"
pgrep -x sxhkd > /dev/null || sxhkd &
killall "polybar"
launch-polybar.sh bar &
killall "cleanfullscreen"
~/.config/bspwm/bin/cleanfullscreen &
#~/.config/bspwm/bin/scratch &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
#bspc config window_gap          0
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config leaf_monocle	true
#bspc config focused_border_color \#a4aa4a
#bspc config normal_border_color \#a4aa4a

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a scratchy sticky=on state=floating rectangle=1200x400+360+0
bspc rule -a Zathura state=tiled
 
#bspc rule -a xfce4-terminal state=floating
# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm >= 0.9.4
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

# graceful kill
#for d in $(bspc query -N);do 
    #bspc node $d -c
#done
